#!/bin/bash

TOKEN=`cat ./TOKEN`

NoteId="$1"
URL="http://127.0.0.1:3001/api/v0/notes/$NoteId"

DDD=`date`

echo -ne "First note\nmultiline text,\nupdated\nat ${DDD}." | \
 http POST "$URL" -- \
  content-type:text/plain \
  x-access-token:$TOKEN

