#!/bin/bash

TOKEN=`cat ./TOKEN`

NoteId="$1"
URL="http://127.0.0.1:3001/api/v0/share/$NoteId"

echo '{ "enabled": true }' | \
http PATCH "$URL" -- content-type:application/json x-access-token:$TOKEN

